repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
    - id: isort
      args: [--check-only]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        args: [--check]
-   repo: local
    hooks:
    -   id: jupyter-cleanup
        name: jupyter-cleanup
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
        files: '\.ipynb$'
        language: system
